### ISSUE TITLE
BottomSheetLayout with a RecycleView

### ISSUE THREAD

**Issue by andrefpc** [qhutch/BottomSheetLayout#3]
I have a problem, because i tried to put a RecycleView into a BottomSheetLayout, but my recycleView don't scroll. Have a way to make this works?

**Comment by Jparrgam** [comment]
not working with recyclerView ? :(

**Comment by qhutch** [comment]
As stated in another issue : 
At the moment, the only touch event I can pass to the views inside the layout is the click, to be able to drag the view from anywhere I need to intercept every touch event and if I detect a click I pass it back to the view.
For the moment the only way yo be able to perform any touch on a view is to create another view at the same level as the layout and animate this view alongside the layout (using the setOnProgressListener method)

**Comment by derohimat** [comment]
I think not only for recyclerView, all widget with scroll function can't work in this library.
